//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    ///<summary>
    ///
    ///</summary>
    public partial class ht_commission
    {
    ///<summary>
    ///
    ///</summary>
        public int id { get; set; }
    ///<summary>
    ///
    ///</summary>
        public int userid { get; set; }
    ///<summary>
    ///
    ///</summary>
        public Nullable<System.DateTime> add_time { get; set; }
    ///<summary>
    ///
    ///</summary>
        public Nullable<int> source_userid { get; set; }
    ///<summary>
    ///
    ///</summary>
        public Nullable<int> source_pre_userid { get; set; }
    ///<summary>
    ///
    ///</summary>
        public Nullable<decimal> total_money { get; set; }
    ///<summary>
    ///
    ///</summary>
        public string source_user_nick { get; set; }
    ///<summary>
    ///
    ///</summary>
        public string source_user_avatar { get; set; }
    ///<summary>
    ///
    ///</summary>
        public Nullable<int> news_id { get; set; }
    }
}
