//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    ///<summary>
    ///
    ///</summary>
    public partial class ht_news_subscribe_relation
    {
    ///<summary>
    ///id
    ///</summary>
        public int id { get; set; }
    ///<summary>
    ///订阅id
    ///</summary>
        public int subscribe_id { get; set; }
    ///<summary>
    ///内容id
    ///</summary>
        public int news_id { get; set; }
    ///<summary>
    ///是否查看
    ///</summary>
        public int is_look { get; set; }
    }
}
