//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_news
    {
        public int id { get; set; }
        public int cateid { get; set; }
        public string cate { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string contact_name { get; set; }
        public string contact_phone { get; set; }
        public Nullable<int> validity_num { get; set; }
        public string validity_unit { get; set; }
        public string start_province { get; set; }
        public string start_city { get; set; }
        public string start_district { get; set; }
        public string start_address { get; set; }
        public string stop_province { get; set; }
        public string stop_city { get; set; }
        public string stop_district { get; set; }
        public string stop_address { get; set; }
        public string tags { get; set; }
        public string use_type { get; set; }
        public string use_img { get; set; }
        public string car_length { get; set; }
        public string car_style { get; set; }
        public string goods_type { get; set; }
        public Nullable<int> goods_weight { get; set; }
        public string goods_weight_unit { get; set; }
        public Nullable<decimal> freight { get; set; }
        public Nullable<System.DateTime> use_time { get; set; }
        public string use_mode { get; set; }
        public string pay_method { get; set; }
        public string other_remark { get; set; }
        public Nullable<int> set_top { get; set; }
        public Nullable<decimal> set_top_money { get; set; }
        public Nullable<decimal> reward_money { get; set; }
        public Nullable<int> recruit_num { get; set; }
        public string imgs { get; set; }
        public int add_userid { get; set; }
        public string add_nickname { get; set; }
        public string add_avatar { get; set; }
        public System.DateTime add_time { get; set; }
        public Nullable<int> update_userid { get; set; }
        public string update_nickname { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<int> audit_userid { get; set; }
        public string audit_nickname { get; set; }
        public Nullable<System.DateTime> audit_time { get; set; }
        public int status { get; set; }
        public int pay_status { get; set; }
        public Nullable<System.DateTime> pay_time { get; set; }
        public string pay_trade_no { get; set; }
        public string order_no { get; set; }
        public int view_num { get; set; }
        public int praise_num { get; set; }
        public int share_num { get; set; }
    
        public virtual ht_news_cate ht_news_cate { get; set; }
    }
}
