//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    ///<summary>
    ///
    ///</summary>
    public partial class ht_news_order
    {
    ///<summary>
    ///
    ///</summary>
        public int id { get; set; }
    ///<summary>
    ///项目Id
    ///</summary>
        public Nullable<int> news_id { get; set; }
    ///<summary>
    ///订单类型
    ///</summary>
        public string type { get; set; }
    ///<summary>
    ///金额
    ///</summary>
        public Nullable<decimal> money { get; set; }
    ///<summary>
    ///支付方式
    ///</summary>
        public string pay { get; set; }
    ///<summary>
    ///支付状态
    ///</summary>
        public Nullable<int> pay_status { get; set; }
    ///<summary>
    ///支付时间
    ///</summary>
        public Nullable<System.DateTime> pay_time { get; set; }
    ///<summary>
    ///交易号
    ///</summary>
        public string pay_trade_no { get; set; }
    ///<summary>
    ///订单号
    ///</summary>
        public string order_no { get; set; }
    ///<summary>
    ///
    ///</summary>
        public string value { get; set; }
    ///<summary>
    ///
    ///</summary>
        public Nullable<System.DateTime> add_time { get; set; }
    ///<summary>
    ///
    ///</summary>
        public Nullable<int> add_userid { get; set; }
    }
}
