//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    ///<summary>
    ///
    ///</summary>
    public partial class ht_news_subscribe
    {
    ///<summary>
    ///
    ///</summary>
        public int id { get; set; }
    ///<summary>
    ///出发省
    ///</summary>
        public string start_province { get; set; }
    ///<summary>
    ///出发市
    ///</summary>
        public string start_city { get; set; }
    ///<summary>
    ///出发区
    ///</summary>
        public string start_district { get; set; }
    ///<summary>
    ///目的省
    ///</summary>
        public string stop_province { get; set; }
    ///<summary>
    ///目的市
    ///</summary>
        public string stop_city { get; set; }
    ///<summary>
    ///目的区
    ///</summary>
        public string stop_district { get; set; }
    ///<summary>
    ///订阅人id
    ///</summary>
        public Nullable<int> add_userid { get; set; }
    ///<summary>
    ///订阅时间
    ///</summary>
        public Nullable<System.DateTime> add_time { get; set; }
    ///<summary>
    ///消息数
    ///</summary>
        public Nullable<int> ncount { get; set; }
    }
}
