//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_news_cate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ht_news_cate()
        {
            this.ht_news = new HashSet<ht_news>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ht_news> ht_news { get; set; }
    }
}
