//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_order_appraise
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> captainuid { get; set; }
        public string contents { get; set; }
        public Nullable<int> deliveryspeed { get; set; }
        public Nullable<int> servicequality { get; set; }
        public Nullable<int> goodsdamage { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
