//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_order
    {
        public int id { get; set; }
        public string orderno { get; set; }
        public string forderno { get; set; }
        public Nullable<int> fpaystatus { get; set; }
        public Nullable<System.DateTime> fpaytime { get; set; }
        public string ftradeno { get; set; }
        public string lorderno { get; set; }
        public Nullable<int> lpaystatus { get; set; }
        public Nullable<System.DateTime> lpaytime { get; set; }
        public string ltradeno { get; set; }
        public Nullable<int> bargainid { get; set; }
        public string bargainno { get; set; }
        public Nullable<int> captainuid { get; set; }
        public Nullable<int> shipperuid { get; set; }
        public Nullable<int> carrierid { get; set; }
        public Nullable<int> freightid { get; set; }
        public Nullable<int> orderstatus { get; set; }
        public Nullable<int> appraisestatus { get; set; }
        public Nullable<int> payid { get; set; }
        public Nullable<decimal> imprestrate { get; set; }
        public Nullable<decimal> finalrate { get; set; }
        public Nullable<decimal> imprestamount { get; set; }
        public Nullable<decimal> finalamount { get; set; }
        public Nullable<int> boatid { get; set; }
        public string boatcode { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> finishtime { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> bid { get; set; }
        public Nullable<decimal> bidprice { get; set; }
        public Nullable<int> isarrive { get; set; }
        public Nullable<System.DateTime> arrivetime { get; set; }
        public Nullable<int> checkstatus { get; set; }
        public Nullable<System.DateTime> checktime { get; set; }
        public Nullable<decimal> checkweight { get; set; }
        public string checkremark { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public Nullable<decimal> delayamount { get; set; }
        public Nullable<decimal> otheramount { get; set; }
        public Nullable<decimal> payablefinalamount { get; set; }
        public Nullable<decimal> realfinalamount { get; set; }
        public Nullable<int> issend { get; set; }
        public Nullable<int> isdissent { get; set; }
        public Nullable<System.DateTime> sendtime { get; set; }
        public Nullable<int> isprofit { get; set; }
        public Nullable<System.DateTime> profittime { get; set; }
        public string profittradeno { get; set; }
        public Nullable<int> ismarginrefund { get; set; }
        public string marginrefundno { get; set; }
        public string marginrefundtradeno { get; set; }
        public Nullable<System.DateTime> marginrefundtime { get; set; }
        public Nullable<decimal> marginrefundamount { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
