//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    ///<summary>
    ///支付方式
    ///</summary>
    public partial class ht_payment
    {
    ///<summary>
    ///
    ///</summary>
        public int id { get; set; }
    ///<summary>
    ///支付方式标题
    ///</summary>
        public string title { get; set; }
    ///<summary>
    ///支付方式说明
    ///</summary>
        public string remark { get; set; }
    ///<summary>
    ///状态: 1.正常 2.禁用
    ///</summary>
        public Nullable<int> status { get; set; }
    ///<summary>
    ///排序
    ///</summary>
        public Nullable<int> sort { get; set; }
    ///<summary>
    ///支付方式手续费
    ///</summary>
        public Nullable<decimal> fee { get; set; }
    ///<summary>
    ///添加时间
    ///</summary>
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
