//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    ///<summary>
    ///
    ///</summary>
    public partial class ht_review
    {
    ///<summary>
    ///
    ///</summary>
        public int id { get; set; }
    ///<summary>
    ///用户id
    ///</summary>
        public int userid { get; set; }
    ///<summary>
    ///用户昵称
    ///</summary>
        public string nickname { get; set; }
    ///<summary>
    ///头像
    ///</summary>
        public string avatar { get; set; }
    ///<summary>
    ///类型(留言、回复)
    ///</summary>
        public string review_type { get; set; }
    ///<summary>
    ///评论内容
    ///</summary>
        public string review_content { get; set; }
    ///<summary>
    ///插入时间
    ///</summary>
        public Nullable<System.DateTime> add_time { get; set; }
    ///<summary>
    ///项目id
    ///</summary>
        public Nullable<int> news_id { get; set; }
    ///<summary>
    ///状态（0待审核 1审核通过 2审核不通过）
    ///</summary>
        public Nullable<int> status { get; set; }
    ///<summary>
    ///
    ///</summary>
        public Nullable<int> review_id { get; set; }
    }
}
