//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_single_page
    {
        public int id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
