//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    ///<summary>
    ///系统配置
    ///</summary>
    public partial class ht_sys_config
    {
    ///<summary>
    ///
    ///</summary>
        public int id { get; set; }
    ///<summary>
    ///键
    ///</summary>
        public string xkey { get; set; }
    ///<summary>
    ///值
    ///</summary>
        public string xvalue { get; set; }
    ///<summary>
    ///说明
    ///</summary>
        public string remark { get; set; }
    ///<summary>
    ///
    ///</summary>
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
