//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_user
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string mobile { get; set; }
        public string realname { get; set; }
        public string avatar { get; set; }
        public string nickname { get; set; }
        public string idcard { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<int> points { get; set; }
        public string openid { get; set; }
        public int issubscribe { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
