//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ht_user
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string email { get; set; }
        public string qq { get; set; }
        public string wechat { get; set; }
        public string address { get; set; }
        public Nullable<int> usertype { get; set; }
        public string mobile { get; set; }
        public string avatar { get; set; }
        public string nickname { get; set; }
        public string realname { get; set; }
        public string company { get; set; }
        public string company_introduction { get; set; }
        public string idcard { get; set; }
        public string usercode { get; set; }
        public string charterno { get; set; }
        public string charter_img { get; set; }
        public string idcard_pros_img { get; set; }
        public string idcard_cons_img { get; set; }
        public string transport_certificate_img { get; set; }
        public Nullable<int> certified_stauts { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<int> isshop { get; set; }
        public Nullable<int> shopstatus { get; set; }
        public string shopname { get; set; }
        public string shopaddress { get; set; }
        public string shopinfo { get; set; }
        public string shopcharteimg { get; set; }
        public string shopcharteno { get; set; }
        public Nullable<int> reputation { get; set; }
        public Nullable<System.DateTime> audittime { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> firstlevel { get; set; }
        public Nullable<int> secondlevel { get; set; }
        public Nullable<int> thirdlevel { get; set; }
        public Nullable<decimal> distributionamount { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
