//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HT.Model
{
    using System;
    using System.Collections.Generic;
    
    ///<summary>
    ///
    ///</summary>
    public partial class sysdiagrams
    {
    ///<summary>
    ///
    ///</summary>
        public string name { get; set; }
    ///<summary>
    ///
    ///</summary>
        public int principal_id { get; set; }
    ///<summary>
    ///
    ///</summary>
        public int diagram_id { get; set; }
    ///<summary>
    ///
    ///</summary>
        public Nullable<int> version { get; set; }
    ///<summary>
    ///
    ///</summary>
        public byte[] definition { get; set; }
    }
}
